services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    image: crop_baskets_backend:latest
    container_name: crop_baskets_backend
    environment:
      RAILS_ENV: production
      PORT: ${RAILS_PORT}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      TZ: Asia/Tokyo
    env_file:
      - .env.prod
    ports:
      - "${RAILS_PORT}:3000"
    restart: always

  nginx:
    build:
      context: ./nginx/
    container_name: crop_baskets_nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env.prod
