services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.dev
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f crop_baskets/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p ${RAILS_PORT}"
    volumes:
      - ./backend:/crop_baskets
      - ./backend/vendor/bundle:/crop_baskets/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    env_file:
      - .env.dev
    ports:
      - "${RAILS_PORT}:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: bash -c "yarn dev"
    volumes:
      - ./frontend:/usr/src/app:delegated
      - node_modules:/usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
      - .env.local
    ports:
      - "${NEXTJS_PORT}:3000"

volumes:
  db-data:
  node_modules:
