services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo

    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f crop_baskets/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/crop_baskets
      - ./backend/vendor/bundle:/crop_baskets/vendor/bundle
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    ports:
      - ${RAILS_PORT}:3000
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build:
    context: ./frontend/
    dockerfile: Dockerfile
    command: bash -c "npm run dev"
    volumes:
      - ./frontend:/usr/src/app:delegated
      - node_modules:/usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${NEXTJS_PORT}:3000

volumes:
  mysql-data:
  node_modules:
