require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - 'db/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'

  TargetRubyVersion: 3.2

# レイアウト関連
Layout/LineLength:
  Max: 130

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# スタイル関連
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

# メトリクス関連
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

# 命名関連
Naming/VariableNumber:
  Enabled: false
