FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

ENV APP_ROOT /crop_baskets
WORKDIR ${APP_ROOT}

COPY Gemfile ${APP_ROOT}/Gemfile
COPY Gemfile.lock ${APP_ROOT}/Gemfile.lock

ENV RAILS_ENV=production
RUN bundle install --without development test

COPY . .

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
