name: ESLint and Prettier

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  eslint_prettier:
    name: ESLint and Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
          cache: 'yarn'
          cache-dependency-path: 'frontend/package.json'
      - name: Run yarn install
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run format
        run: yarn format
